# Generated by Django 5.0 on 2023-12-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='jugador',
            name='numero',
            field=models.CharField(max_length=3),
        ),
    ]
